networkapp/urls.py
from django.conf.urls import re_path
from networkapp import views

app_name = 'networkapp'

urlpatterns = [
    re_path(r'dashboard/$',views.dashboard,name='dashboard'),
    re_path(r'register/$',views.register,name='register'),
    re_path(r'user_login/$',views.user_login,name='user_login'),
    re_path(r'device_discovery/$',views.device_discovery,name='device_discovery'),
    re_path(r'adddevice_credential/$',views.add_device_credential,name='add_device_credential'),
    re_path(r'add_device_commands/$',views.add_device_commands,name='add_device_commands'),
    re_path(r'fetch_device_configuration/$',views.fetch_device_configuration,name='fetch_device_configuration'),
    re_path(r'device_configuration/$',views.device_configuration,name='device_configuration'),
    re_path(r'getDashboardDetails/$',views.getDashboardDetails,name='getDashboardDetails'),
    re_path(r'device_access/$',views.device_access,name='device_access')
]

networkproject/urls.py
from django.contrib import admin
from networkapp import views
from django.urls import path,re_path,include

urlpatterns = [
    re_path(r'^$',views.index,name='index'),
    path('admin/', admin.site.urls),
    re_path(r'networkapp/',include('networkapp.urls')),
    re_path(r'^logout/$',views.user_logout,name='logout'),
    re_path(r'home/',views.home,name='home'),
    re_path(r'^accounts/login/$', views.index)
]

networkapp/models.py
from django.db import models
from django.utils import timezone
from django.urls import reverse
from django.contrib.auth.models import User
# Create your models here.

class UserProfileInfo(models.Model):
    user = models.OneToOneField(User,on_delete=models.CASCADE)
    full_name = models.CharField(max_length=50)
    profile_pic = models.ImageField(upload_to='profile_pics',blank=True)

class DeviceCredentialDetail(models.Model):
    device_ip = models.CharField(max_length=15,unique=True)
    device_username = models.CharField(max_length=50)
    device_password = models.CharField(max_length=50)

class DeviceCommandInfo(models.Model):
    device_command =models.CharField(max_length=100,unique=True)
    command_name = models.CharField(max_length=30,unique=True)

class CollectionInfo(models.Model):
    auto_increment_id = models.AutoField(primary_key=True)
    filepath = models.CharField(max_length=100,unique=True)
    created_on = models.DateTimeField(auto_now=True)

networkapp/forms.py
from django import forms
from django.contrib.auth.models import User
from networkapp.models import UserProfileInfo
from networkapp.models import DeviceCredentialDetail,DeviceCommandInfo

class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())
    class Meta():
        model = User
        fields = ('username','email','password')
        labels = {
        "username": "User Id"
        }

class UserProfileInfoForm(forms.ModelForm):
    full_name = forms.CharField(required=True)
    class Meta():
        model = UserProfileInfo
        fields = ('full_name','profile_pic')

class DeviceCredentialForm(forms.ModelForm):
    device_password = forms.CharField(widget=forms.PasswordInput())
    device_ip = forms.CharField(required=True,widget=forms.TextInput(attrs={'class':'form-control' , 'autocomplete': 'off','pattern':'\d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3}', 'title':'Enter IP Address ','onblur':'ipvalidation(this.value);'}))
    device_username = forms.CharField(required=True,widget=forms.TextInput(attrs={'class':'form-control' , 'autocomplete': 'off', 'title':'Enter Username'}))
    class Meta():
        model = DeviceCredentialDetail
        fields =('device_ip','device_username','device_password')

class DeviceCommandForm(forms.ModelForm):
    class Meta():
        model = DeviceCommandInfo
        fields = ('device_command','command_name')
        labels = {
            "device_command": "Enter command",
             "command_name": "Enter short name for command",
        }

networkapp/views.py
from django.shortcuts import render
from networkapp.forms import UserForm, UserProfileInfoForm, DeviceCredentialForm, DeviceCommandForm
from django.contrib.auth import authenticate, login, logout
from django.http import HttpResponseRedirect, HttpResponse
from django.urls import reverse
from django.contrib.auth.decorators import login_required
from networkapp.models import DeviceCommandInfo, DeviceCredentialDetail,CollectionInfo
import numpy as np
import json
import datetime
import os

import networkapp.ssh_connection as sshcon
from networkapp.device_discovery import DEVICEDISCOVERY
from networkapp.ssh_connection import ssh_connection
from networkapp.create_threads import create_threads
from networkapp.device_access_varification import DEVICE_ACCESS_VERIFICATION
# Create your views here.


def index(request):
    urllink=''
    if request.user.is_authenticated:
        urllink='networkapp/home.html'
    else:
        urllink='networkapp/index.html'
    return render(request,urllink)

@login_required(login_url='/accounts/login/')
def dashboard(request):
    return render(request, 'networkapp/dashboard.html')

def getDashboardDetails(request):
    inactivecount=0
    activecount=0
    devicelist=[]
    devicelistArray=[]
    if request.method == 'GET': 
        d = DEVICEDISCOVERY()
        devicelist = DeviceCredentialDetail.objects.values('device_ip')
        for deviceip in devicelist:
            devicelistArray.append(deviceip.get('device_ip'))
        print("requet from ajax : ",devicelistArray)
        d.ping_range(devicelistArray)
        for ip,value in d.ping_res.items():
            print(value)
            if value == "active":
                activecount=activecount+1
            else:
                inactivecount=inactivecount+1
    data = {'inactivecount':inactivecount,'activecount':activecount}
    print(data)
    return HttpResponse(json.dumps(data), content_type="application/json")

@login_required(login_url='/accounts/login/')
def home(request):
    return render(request, 'networkapp/home.html')


@login_required(login_url='/accounts/login/')
def user_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse('index'))

@login_required(login_url='/accounts/login/')
def register(request):
    registered = False
    if request.method == "POST":
        user_form = UserForm(data=request.POST)
        profile_form = UserProfileInfoForm(data=request.POST)

        if user_form.is_valid() and profile_form.is_valid():
            user = user_form.save()
            user.set_password(user.password)
            user.save()

            profile = profile_form.save(commit=False)
            profile.user = user

            if 'profile_pic' in request.FILES:
                profile.profile_pic = request.FILES['profile_pic']

            profile.save()
            registered = True
        #else:
            #print(user_form.errors, profile_form.errors)
    else:
        user_form = UserForm()
        profile_form = UserProfileInfoForm()

    return render(request, 'networkapp/registration.html', {'user_form': user_form, 'profile_form': profile_form, 'registered': registered})


def user_login(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')

        user = authenticate(username=username, password=password)

        if user:
            if user.is_active:
                login(request, user)
                return HttpResponseRedirect(reverse('home'))
            else:
                return HttpResponse("ACCOUNT NOT ACTIVE")
        else:
             #print("Someone tried to login and failes !")
             #print("Username: {} and password {}".format(username, password))
            return HttpResponse("Invalid Login Details")
    else:
        return render(request, 'networkapp/index.html', {})


@login_required(login_url='/accounts/login/')
def device_discovery(request):
    D = DEVICEDISCOVERY()
    D.ping_res.clear()
    list = []
    if request.method == 'POST':
        fromip = request.POST.get('fromip')
        toip = request.POST.get('toip')
        if fromip == toip:
            list.append(fromip)
        else:
            list = D.ips(fromip, toip)
            list.append(toip)

        print("List of ip : ",list)
        D.ping_range(list)
         #print(D.ping_res)
    return render(request, 'networkapp/device_discovery.html', {'new_dict': D.ping_res, 'activedevice_count': D.activedevice_count, 'inactivedevice_count': D.inactivedevice_count})


@login_required(login_url='/accounts/login/')
def fetch_device_configuration(request):
    sshcon.device_output.clear()
    ip_list = []
    password_list=[]
    username_list=[]
    unrechable_device_list=[]
    rechable_ip_list=[]
    invalid_cred_device_list=[]
    d = DEVICEDISCOVERY()
    dav = DEVICE_ACCESS_VERIFICATION()  

    commandlist = DeviceCommandInfo.objects.all()
    devicelist = DeviceCredentialDetail.objects.values('device_ip')

    if request.method == "POST":
        command = request.POST.get('selcommand')
        deviceip = request.POST.get('seldeviceip')
         
        if deviceip == "all" :
            device_cred_query = DeviceCredentialDetail.objects.all()
             #print(device_cred_query)
            for device_cred in device_cred_query:
                username = device_cred.device_username
                 #print(username)
                username_list.append(username)
                password = device_cred.device_password
                password_list.append(password)
                deviceip = device_cred.device_ip
                ip_list.append(deviceip)
        else:
            ip_list.append(deviceip)
            usernames = DeviceCredentialDetail.objects.values('device_username').filter(device_ip=deviceip)
            passwords = DeviceCredentialDetail.objects.values('device_password').filter(device_ip=deviceip)
            for user in usernames:
                username = user.get('device_username')
                username_list.append(username)
            for user in passwords:
                password = user.get('device_password')
                password_list.append(password)
        
        rechable_ip_list = list(ip_list)
        d.ping_range(ip_list)
        index_list=[]
        for device, value in d.ping_res.items():
            if value == "inactive":
                unrechable_device_list.append(device)
                index_list.append(ip_list.index(device))

        username_list=np.delete(username_list, index_list).tolist()
        password_list=np.delete(password_list, index_list).tolist()
        rechable_ip_list=np.delete(rechable_ip_list, index_list).tolist()

        if len(rechable_ip_list) > 0 :
            dav.verifydav(rechable_ip_list,username_list,password_list)

        dav_index_list=[]
        for device, value in dav.dav_res.items():
            if value == "failed":
                invalid_cred_device_list.append(device)
                dav_index_list.append(ip_list.index(device))

        if len(rechable_ip_list) > 0 :
            username_list=np.delete(username_list, dav_index_list).tolist()
            password_list=np.delete(password_list, dav_index_list).tolist()
            rechable_ip_list=np.delete(rechable_ip_list, dav_index_list).tolist()        
            
            create_threads(rechable_ip_list,username_list,password_list,command,ssh_connection)

        ts = datetime.datetime.now().timestamp()

        try:  
            os.mkdir("data/"+command)
        except OSError:  
            print ("Creation of the directory %s failed")

        for ip,output in sshcon.device_output.items():
            filepath="data/"+command+"/"+ip+"-"+str(ts)+".txt"
            with open(filepath, 'w+') as f:
                f.write(output+'')
                f.flush()
                f.close()
            collection=CollectionInfo(filepath=filepath,created_on=datetime.datetime.now().time())
            collection.save()
            
         #print("invalid cred list :",invalid_cred_device_list)
         #print("unrechable cred list :",unrechable_device_list)

    return render(request, 'networkapp/fetch_device_configuration.html', {'commandlist': commandlist, 'devicelist': devicelist,'commandoutput' : sshcon.device_output,'invalidcredential':invalid_cred_device_list,'unreachabledevice':unrechable_device_list})


@login_required(login_url='/accounts/login/')
def add_device_credential(request):
    result = False
    if request.method == "POST":
        device_credential_form = DeviceCredentialForm(data=request.POST)
        if device_credential_form.is_valid():
            device_details = device_credential_form.save()
            device_details.save()
            result = True
        else:
             #print(device_credential_form.errors)
            result = False
    else:
        device_credential_form = DeviceCredentialForm()
    return render(request, 'networkapp/add_credential.html', {'device_credential_form': device_credential_form, 'result': result})

@login_required(login_url='/accounts/login/')
def add_device_commands(request):
    result = False
    if request.method == "POST":
        device_command_form = DeviceCommandForm(data=request.POST)
        if device_command_form.is_valid():
            device_command = device_command_form.save()
            device_command.save()
            result = True
        else:
             #print(device_command_form.errors)
            result = False
    else:
        device_command_form = DeviceCommandForm()
    return render(request, 'networkapp/add_commands.html', {'device_command_form': device_command_form, 'result': result})

@login_required(login_url='/accounts/login/')
def device_configuration(request):
    sshcon.device_output.clear()
    ip_list = []
    password_list=[]
    username_list=[]
    unrechable_device_list=[]
    rechable_ip_list=[]
    invalid_cred_device_list=[]
    d = DEVICEDISCOVERY()

templates/networkapp/add_commands.html
{% extends "networkapp/home.html"%}
{% block body_block %}
{% load crispy_forms_tags %}
<div class="row">
    <div class="col-sm-9 col-md-7 col-lg-12 mx-auto">
        <h3 class="card-title text-center">Add Commands</h3>
        <hr />
        <p id="errormsg"></p>
        {% if result == True %}
        <div class='alert alert-success'><strong>Success ! </strong> Command saved</div>
        {% endif %}
        <form enctype="multipart/form-data" method="post">
            {% csrf_token %}
            {{ device_command_form | crispy }}
            <input type="submit" class="btn btn-success btn-md" value="Submit" />
            <input type="reset" class="btn btn-danger btn-md" value="Reset" />
        </form>
    </div>
</div>
{% endblock %}

templates/networkapp/add_credential.html
{% extends "networkapp/home.html"%}
{% block body_block %}
{% load crispy_forms_tags %}
<div class="container">
    <div class="row justify-content-center align-items-center h-100">
        <div class="col-lg-12 clo-sm-12">
            <h4>Add Device credential</h4>
            <hr />
            <p id="errormsg"></p>
            {% if result == True %}
            <div class='alert alert-success'><strong>Success ! </strong> Credential saved</div>
            {% endif %}
            <form enctype="multipart/form-data" method="post">
                {% csrf_token %}
                {{ device_credential_form |crispy }}
                <input type="submit" class="btn btn-success btn-md" value="Submit" />
                <input type="reset" class="btn btn-danger btn-md" value="Reset" />
            </form>
        </div>
    </div>
</div>
<script>
    function ipvalidation(ip) {
        if (ip != "") {
            var octet_list = ip.split('.');
            if ((octet_list.length == 4) && (octet_list[0] >= 1 && octet_list[0] <= 233) && (octet_list[0] != 127) && (octet_list[0] != 169 || octet_list[1] != 254) && ((octet_list[1] >= 0 && octet_list[1] <= 255) && (octet_list[2] >= 0 && octet_list[2] <= 255) && (octet_list[3] >= 0 && octet_list[3] <= 255)))
                document.getElementById("errormsg").innerHTML = "";
            else
                document.getElementById("errormsg").innerHTML = "<div class='alert alert-danger'><strong>Error</strong> Invalid ip address</div>";
        }
    }
</script>
{% endblock %}

templates/networkapp/base.html
{% load staticfiles %}
<!doctype html>
<html lang="en">

<head>
  <title>CNM</title>
  <!-- Required meta tags -->
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <!-- Bootstrap CSS here -->
  <link rel="icon" type="image/png" href="{% static 'img/favicon.ico' %}">
  <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet" />
  <link href="{% static 'css/light-bootstrap-dashboard.css' %}" rel="stylesheet" />
  <style type="text/css">
    body {
      background-image: url("{% static 'img/back-2847_1920.jpg' %}");
      background-color:beige;
    }
  </style>
</head>
<body>
  <div class="container">
    {% block body_block %}
    {% endblock %}
  </div>
</body>
</html>

templates/networkapp/dashboard.html
{% extends "networkapp/home.html"%}
{% block body_block %}
<div class="row">
    <div class="col-md-4">
        <div class="card ">
            <div class="card-header ">
                <h4 class="card-title">Network Statistics</h4>
                <p class="card-category">Network device status</p>
            </div>
            <div class="card-body ">
                <div id="chartPreferences" class="ct-chart ct-perfect-fourth"></div>
            </div>
            <div class="card-footer ">
                <div class="legend">
                    <i class="fa fa-circle text-info"></i> Active
                    <i class="fa fa-circle text-danger"></i> Inactive
                </div>
                <hr>
                <div class="stats">
                    <i class="fa fa-clock-o"></i> Status 10 min ago
                </div>
            </div>
        </div>
    </div>
    <div class="col-md-8">
        <div class="card ">
            <div class="card-header ">
                <h4 class="card-title">Application Usage</h4>
                <p class="card-category">24 Hours performance</p>
            </div>
            <div class="card-body ">
                <div id="chartHours" class="ct-chart"></div>
            </div>
            <div class="card-footer ">
                <div class="legend">
                    <i class="fa fa-circle text-info"></i> Open
                    <i class="fa fa-circle text-danger"></i> Click
                    <i class="fa fa-circle text-warning"></i> Click Second Time
                </div>
                <hr>
                <div class="stats">
                    <i class="fa fa-history"></i> Updated 3 minutes ago
                </div>
            </div>
        </div>
    </div>
</div>
</div>
{% endblock %}

templates/networkapp/dashboard_temp.html
{% block body_block %}
<div class="row">
    <div class="col-md-4">
        <div class="card ">
            <div class="card-header ">
                <h4 class="card-title">Network Statistics</h4>
                <p class="card-category">Network device status</p>
            </div>
            <div class="card-body ">
                <div id="chartPreferences" class="ct-chart ct-perfect-fourth"></div>
            </div>
            <div class="card-footer ">
                <div class="legend">
                    <i class="fa fa-circle text-info"></i> Active
                    <i class="fa fa-circle text-danger"></i> Inactive
                </div>
                <hr>
                <div class="stats">
                    <i class="fa fa-clock-o"></i> Status 10 min ago
                </div>
            </div>
        </div>
    </div>
    <div class="col-md-8">
        <div class="card ">
            <div class="card-header ">
                <h4 class="card-title">Application Usage</h4>
                <p class="card-category">24 Hours performance</p>
            </div>
            <div class="card-body ">
                <div id="chartHours" class="ct-chart"></div>
            </div>
            <div class="card-footer ">
                <div class="legend">
                    <i class="fa fa-circle text-info"></i> Open
                    <i class="fa fa-circle text-danger"></i> Click
                    <i class="fa fa-circle text-warning"></i> Click Second Time
                </div>
                <hr>
                <div class="stats">
                    <i class="fa fa-history"></i> Updated 3 minutes ago
                </div>
            </div>
        </div>
    </div>
</div>
</div>
{% endblock %}

templates/networkapp/device_configuration.html
{% extends "networkapp/home.html"%}
{% block body_block %}
<div class="row">
    <div class="col-sm-9 col-md-7 col-lg-12 mx-auto">
                <h3 class="card-title text-center">Device configuration</h3>
                <hr />
                <p id="errormsg"></p>
                {% if result == True %}
                <div class='alert alert-success'><strong>Success ! </strong> Command saved</div>
                {% endif %}
                <form enctype="multipart/form-data" method="post">
                    {% csrf_token %}
                    <div class="form-group">
                        <label for="commandlist">Command:</label>
                        <textarea class="form-control" rows="8" style="height:auto" id="commandlist" onblur="splitcommand();"  name="commandlist"></textarea>
                    </div>
                    <div class="form-group">
                        <label for="seldeviceip">Select Device:</label>
                        <select class="form-control" id="seldeviceip" name="seldeviceip">
                            {% for device in devicelist %}
                            <option value='{{device.device_ip}}'> {{device.device_ip}}</option>
                            {% endfor %}
                        </select>
                    </div>
                    <input type="hidden" name="commands" id="commands" />
                    <input type="submit" class="btn btn-success btn-md" value="Submit" />
                    <input type="reset" class="btn btn-danger btn-md" value="Cancel" />
                </form>
    </div>
</div>
<script>
function splitcommand(){
    var textArea = document.getElementById("commandlist");
    var arrayOfLines = textArea.value.split("\n"); 
    var finalcommandlist = arrayOfLines.join();
    document.getElementById("commands").value=finalcommandlist;
}
</script>
{% endblock %}

templates/networkapp/device_discovery.html
{% extends "networkapp/home.html"%}
{% block body_block %}
{% load crispy_forms_tags %}
<div class="container">
    <h3>Discover Device</h3>
    <p  id="errormsg"></p>
    <form action="{% url 'networkapp:device_discovery' %}" method="post">
        {% csrf_token %}
        <div class="row">
            <div class="col-lg-4">
                <div class="form-label-group">
                    <label for="fromip">Starting  IP Address</label>
                    <input type="text" id="fromip" onblur="ipvalidation(this.value);" name="fromip" class="form-control" placeholder="Starting  IP Address"
                        required autofocus>
                </div>
            </div>
            <div class="col-lg-4">
                <div class="form-label-group">
                    <label for="toip">Ending IP Address</label>
                    <input type="test" id="toip" name="toip" onblur="ipvalidation(this.value);" class="form-control" placeholder="Ending  IP Address"
                        required>
                </div>
            </div>
            <div class="col-lg-4">
                <div class="form-label-group">
                    <label for="toip">&nbsp;</label>
                    <input type="submit" class="btn btn-success btn-md btn-block" value="Discover" />
                </div>
            </div>
        </div>
        <hr/>
        {%if new_dict and not invalidip %}
        <div class="row">
            <div class="col-lg-8">
                <table class="table table-striped table-bordered">
                    <thead>
                        <th>Device Ip</th>
                        <th>status</th>
                    </thead>
                    <tbody>
                        {% for key, value in new_dict.items %}
                        <tr>
                        <td>{{key}}</td>
                        <td>
                            {% if value == "inactive" %}
                            <span style="color: red">{{value}}</span>
                            {% else %}
                            <span style="color:green">{{value}}</span>
                            {%endif%}
                        </td>
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
            <div class="col-lg-4">
                    <table class="table table-striped table-bordered">
                            <thead>
                                <th>Active Devices</th>
                                <th>Inactive Devices</th>
                            </thead>
                            <tbody>
                                <td>{{activedevice_count}}</td>
                                <td>{{inactivedevice_count}}</td>
                            </tbody>
                    </table>                            
            </div>
        </div>
        {% else %}
        {%endif%}
</div>
<script>
    function ipvalidation(ip){
        if(ip != ""){
            var octet_list = ip.split('.');
            if((octet_list.length == 4) && (octet_list[0] >=1 && octet_list[0] <= 233) && (octet_list[0] != 127) && (octet_list[0] != 169 || octet_list[1] != 254) && ((octet_list[1] >=0 && octet_list[1] <= 255) && (octet_list[2] >=0 && octet_list[2] <= 255) && (octet_list[3] >=0 && octet_list[3] <= 255)))
                document.getElementById("errormsg").innerHTML="";
            else
                document.getElementById("errormsg").innerHTML="<div class='alert alert-danger'><strong>Error</strong> Invalid ip address</div>";
        }
    }
    </script>
{% endblock %}

templates/networkapp/fetch_device_configuration.html
{% extends "networkapp/home.html"%}
{% block body_block %}
{% load crispy_forms_tags %}
<div class="container">
    <div class="row justify-content-center align-items-center h-100">
        <div class="col-lg-12 clo-sm-12">
            <h4>Get Device Details</h4>
            <hr/>
            <p id="errormsg"></p>
            {% if result == True %}
            <div class='alert alert-success'><strong>Success ! </strong> Credetial saved</div>
            {% endif %}

            <form enctype="multipart/form-data" method="post">
                {% csrf_token %}
                <div class="form-group">
                    <label for="selcommand">Select Command:</label>
                    <select class="form-control" id="selcommand" name="selcommand">
                        {% for command in commandlist %}
                        <option value='{{command.device_command}}'> {{command.device_command}}</option>
                        {% endfor %}
                    </select>
                </div>
                <div class="form-group">
                    <label for="seldeviceip">Select Device:</label>
                    <select class="form-control" id="seldeviceip" name="seldeviceip">
                        <option value='all'>All</option>
                        {% for device in devicelist %}
                        <option value='{{device.device_ip}}'> {{device.device_ip}}</option>
                        {% endfor %}
                    </select>
                </div>
                <input type="submit" class="btn btn-success btn-md" value="fetch" />
            </form>
            <hr/>
            <div class="row">
                {%if unreachabledevice %}
                <div class="col-lg-6">
                    <table class="table table-striped table-bordered">
                        <thead>
                            <tr>
                                <th>Unreachable Device</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for ip in unreachabledevice %}
                            <tr>
                                <td> {{ip}}</td>
                            </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                </div>
                {%endif%}
                {% if invalidcredential %}
                <div class="col-lg-6">
                    <table class="table table-striped table-bordered">
                        <thead>
                            <tr>
                                <th>Ivalid Credential for Device</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for ip in invalidcredential %}
                            <tr>
                                <td> {{ip}}</td>
                            </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                </div>
                {%endif%}
            </div>
            {% if commandoutput %}
            <div class="row">
                <div class="col-lg-12">
                    <table class="table table-striped table-bordered">
                        <thead>
                            <tr>
                                <th>Device Ip</th>
                                <th>Command output</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for ip, output in commandoutput.items %}
                            <tr>
                                <td> {{ip}}</td>
                                <td> {{output|safe}}</td>
                                {% endfor %}
                            </tr>
                        </tbody>
                    </table>
                </div>
            </div>
            {%endif %}
        </div>
    </div>
</div>
{% endblock %}

templates/networkapp/index.html
{% extends "networkapp/base.html"%}
{% block body_block %}
<div class="row">
      <div class="col-sm-9 col-md-7 col-lg-4 mx-auto">
        <div class="card card-signin my-5" style="background-color: transparent">
          <div class="card-body" >
            <h3 class="card-title text-center" style="color: white">CENTRALIZED NETWORK MANAGER </h3>
            <hr/>
            <form action="{% url 'networkapp:user_login' %}" method="post" class="form-signin">
             {% csrf_token %}
              <div class="form-label-group">
                <input type="text" id="username" name="username" style="text-align: center" class="form-control" placeholder="Enter Username" required autofocus>
              </div>
<br/>
              <div class="form-label-group">
                <input type="password" id="password" name="password" style="text-align: center" class="form-control" placeholder=" Enter Password" required>
              </div>
              <div class="custom-control custom-checkbox mb-3">
                <input type="checkbox" class="custom-control-input" id="customCheck1">
               </div>
              <button class="btn btn-md btn-success btn-block text-uppercase" id="signin" style="color: white;background-color:#28a745" type="submit">Sign in</button>
            </form>
          </div>
        </div>
      </div>
    </div>
{% endblock %}